<a href="https://colab.research.google.com/github/Dreaming-world/learn_tensorflow_nlp/blob/master/1_nlp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
from __future__ import absolute_import, division, print_function, unicode_literals

# 安装 TensorFlow
try:
  # Colab only
  %tensorflow_version 2.x
except Exception:
    pass

import tensorflow as tf
print(tf.__version__)

2.2.0-rc4


In [0]:
import pandas as pd
import gensim
import numpy as np
import jieba

In [10]:
sentence = [
            '机器学习我的理解就是把各种原始的东西变成机器可以理解的东西，然后再用各种机器学习算法来做操作',
            '网上大部分都是处理英文文本的资料，本文就以中文文本为例，将原始的文本经过预处理得到文本向量'
]
data = []
for ele in sentence:
  data.append(list(jieba.cut(ele)))
print(data)

[['机器', '学习', '我', '的', '理解', '就是', '把', '各种', '原始', '的', '东西', '变成', '机器', '可以', '理解', '的', '东西', '，', '然后', '再用', '各种', '机器', '学习', '算法', '来', '做', '操作'], ['网上', '大部分', '都', '是', '处理', '英文', '文本', '的', '资料', '，', '本文', '就', '以', '中文', '文本', '为例', '，', '将', '原始', '的', '文本', '经过', '预处理', '得到', '文本', '向量']]


In [0]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [12]:
tokenizer = Tokenizer(oov_token='UNK')
tokenizer.fit_on_texts(data)
print( tokenizer.word_counts)
print( tokenizer.word_index)
print( tokenizer.word_docs) 
print( tokenizer.index_docs)
print( tokenizer.texts_to_sequences(data))
print( tokenizer.texts_to_matrix(data))
#sklearn保存方法，通常用来保存模型
from sklearn.externals import joblib 
joblib.dump(tokenizer,'dataFile.pkl')  #模型保存
tokenizer1 = joblib.load('dataFile.pkl') #模型载入
print(tokenizer1.word_index)

OrderedDict([('机器', 3), ('学习', 2), ('我', 1), ('的', 5), ('理解', 2), ('就是', 1), ('把', 1), ('各种', 2), ('原始', 2), ('东西', 2), ('变成', 1), ('可以', 1), ('，', 3), ('然后', 1), ('再用', 1), ('算法', 1), ('来', 1), ('做', 1), ('操作', 1), ('网上', 1), ('大部分', 1), ('都', 1), ('是', 1), ('处理', 1), ('英文', 1), ('文本', 4), ('资料', 1), ('本文', 1), ('就', 1), ('以', 1), ('中文', 1), ('为例', 1), ('将', 1), ('经过', 1), ('预处理', 1), ('得到', 1), ('向量', 1)])
{'UNK': 1, '的': 2, '文本': 3, '机器': 4, '，': 5, '学习': 6, '理解': 7, '各种': 8, '原始': 9, '东西': 10, '我': 11, '就是': 12, '把': 13, '变成': 14, '可以': 15, '然后': 16, '再用': 17, '算法': 18, '来': 19, '做': 20, '操作': 21, '网上': 22, '大部分': 23, '都': 24, '是': 25, '处理': 26, '英文': 27, '资料': 28, '本文': 29, '就': 30, '以': 31, '中文': 32, '为例': 33, '将': 34, '经过': 35, '预处理': 36, '得到': 37, '向量': 38}
defaultdict(<class 'int'>, {'算法': 1, '理解': 1, '学习': 1, '，': 2, '的': 2, '机器': 1, '原始': 2, '做': 1, '就是': 1, '我': 1, '操作': 1, '然后': 1, '各种': 1, '再用': 1, '变成': 1, '来': 1, '东西': 1, '可以': 1, '把': 1, '都': 1, '预处理': 1, '将': 1, '是': 

In [13]:
tokenizer1.texts_to_sequences(['你好'])

[[1]]

In [0]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [16]:
maxlength = 40
pad_sequences(tokenizer.texts_to_sequences(data),
              maxlen=maxlength,dtype='int32',
              padding='pre',truncating='pre',value=0)

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  4,  6, 11,
         2,  7, 12, 13,  8,  9,  2, 10, 14,  4, 15,  7,  2, 10,  5, 16,
        17,  8,  4,  6, 18, 19, 20, 21],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 22, 23,
        24, 25, 26, 27,  3,  2, 28,  5, 29, 30, 31, 32,  3, 33,  5, 34,
         9,  2,  3, 35, 36, 37,  3, 38]], dtype=int32)

In [17]:
# 求平均值
data = [
        [[1.0,2,3],[3,4,5]],
        [[6,8,7],[7,7,7]],
        ]
# data = np.array(data)
x = tf.reduce_mean(data, [1], keepdims=False)
# x = tf.reduce_mean(x, [1], keepdims=True)
y = [[2,2],[3,3],[4.0,4]]
b =[1,2]
tf.matmul(x, y)+1

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[30. , 30. ],
       [64.5, 64.5]], dtype=float32)>

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([3, 7])>

In [18]:
w_initer = tf.random_normal_initializer()
a = tf.Variable(name='w1', 
                initial_value=w_initer(shape=(2,1),dtype=tf.float16))
print(a)
b = tf.Variable(name='w1', 
                initial_value=w_initer(shape=(1,1),dtype=tf.float16))
print(b)
tf.matmul(a,b)

<tf.Variable 'w1:0' shape=(2, 1) dtype=float16, numpy=
array([[-0.04288],
       [-0.08356]], dtype=float16)>
<tf.Variable 'w1:0' shape=(1, 1) dtype=float16, numpy=array([[0.0781]], dtype=float16)>


<tf.Tensor: shape=(2, 1), dtype=float16, numpy=
array([[-0.00335 ],
       [-0.006527]], dtype=float16)>

In [19]:
!pip install pinyin

     |████████████████████████████████| 3.6MB 3.5MB/s 
  Created wheel for pinyin: filename=pinyin-0.4.0-cp36-none-any.whl size=3630485 sha256=5540a3c2ffac99f7c868ad3f0a48ff79b586017b2defe92f58aa6537b0c91e2d
  Stored in directory: /root/.cache/pip/wheels/bd/90/5a/e9844998f3e67b29c5bbca9dc20b5c76f936a45ea77f78e4a9
Successfully built pinyin


In [21]:
# code for NNLM
import tensorflow as tf
import numpy as np
import pinyin


tf.reset_default_graph()

word_sentences = [ "我 喜  欢 狗 , 但是 我 不 喜欢 买 狗粮", 
             "我 最爱 咖啡 ， 但是 我 得 加 糖", 
             "我 讨厌 牛奶 ， 可是 我 知道 牛奶 有助于 消化"]
# 拼音组成
pinyin_sentences = []
for sen in word_sentences:
  pinyin_sentences.append(' '.join([pinyin.get(word, format="strip", delimiter="") for word in sen.split(" ")]))


sentences = []
sentences.extend(word_sentences)
sentences.extend(pinyin_sentences)

word_list = " ".join(sentences).split()
word_list = list(set(word_list))
word_dict = {w: i for i, w in enumerate(word_list)}
print("word_dict:", word_dict)
number_dict = {i: w for i, w in enumerate(word_list)}
print("number_dict:", number_dict)
n_class = len(word_dict) # number of Vocabulary

# NNLM Parameter
n_step = 4 # number of steps ['i like', 'i love', 'i hate']
n_hidden = 2 # number of hidden units

def make_batch(word_sentences, pinyin_sentences):
    input_batch = []
    target_batch = []

    for word_sen, pinyin_sen in zip(word_sentences, pinyin_sentences):
        word = word_sen.split()
        pinyin_word = pinyin_sen.split()
        for i in range(n_step, len(word)):
          input_word = [word_dict[n] for n in word[i-n_step // 2:i]]
          input_pinyin = [word_dict[n] for n in pinyin_word[i-n_step //2:i]]
          input_word.extend(input_pinyin)
          print(input_word)
          target = word_dict[word[i]]
          input_batch.append(np.eye(n_class)[input_word])
          target_batch.append(np.eye(n_class)[target])

          # print("input:", input)
          # print("target:", target)
          # print("input_batch", input_batch)
          # print("target_batch", target_batch)

    return input_batch, target_batch

# Model
X = tf.placeholder(tf.float32, [None, n_step, n_class]) # [batch_size, number of steps, number of Vocabulary]
Y = tf.placeholder(tf.float32, [None, n_class])

input = tf.reshape(X, shape=[-1, n_step * n_class]) # [batch_size, n_step * n_class]
H = tf.Variable(tf.random_normal([n_step * n_class, n_hidden]))
d = tf.Variable(tf.random_normal([n_hidden]))
U = tf.Variable(tf.random_normal([n_hidden, n_class]))
b = tf.Variable(tf.random_normal([n_class]))

tanh = tf.nn.tanh(d + tf.matmul(input, H)) # [batch_size, n_hidden]
model = tf.matmul(tanh, U) + b # [batch_size, n_class]

cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(logits=model, labels=Y))
optimizer = tf.train.AdamOptimizer(0.001).minimize(cost)
prediction =tf.argmax(model, 1)

# Training
init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)

input_batch, target_batch = make_batch(word_sentences, pinyin_sentences)

for epoch in range(15000):
    _, loss = sess.run([optimizer, cost], feed_dict={X: input_batch, Y: target_batch})
    if (epoch + 1)%1000 == 0:
        print('Epoch:', '%04d' % (epoch + 1), 'cost =', '{:.6f}'.format(loss))

# Predict
def model_predict(word1, word2, word3, word4):
  id1 = word_dict[word1]
  id2 = word_dict[word2]
  id3 = word_dict[word3]
  id4 = word_dict[word4]

  test_x = []
  test_x.append(np.eye(n_class)[[id1, id2, id3, id4]])
  predict =  sess.run([prediction], feed_dict={X: test_x})
  predict_word = number_dict[predict[0][0]]
  print(word1, word2, "---->", predict_word)

model_predict("牛奶","有助于", "niunai", "youzhuyu")


AttributeError: ignored

In [22]:

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import collections
import math
import os
import random
import zipfile
import numpy as np    #在引用包方面，对源码进行了一些修改，因为源码应该是基于python3的 
import urllib         #而我使用的python2
import tensorflow as tf

# Step 1: Download the data.
url = 'http://mattmahoney.net/dc/'

def maybe_download(filename, expected_bytes):
  """Download a file if not present, and make sure it's the right size."""
  if not os.path.exists(filename):
    filename, _ = urllib.urlretrieve(url + filename, filename)
  statinfo = os.stat(filename)
  if statinfo.st_size == expected_bytes:
    print('Found and verified', filename)
  else:
    print(statinfo.st_size)
    raise Exception(
        'Failed to verify ' + filename + '. Can you get to it with a browser?')
  return filename

filename = maybe_download('text8.zip', 31344016)


# Read the data into a list of strings.
def read_data(filename):
  """Extract the first file enclosed in a zip file as a list of words"""
  with zipfile.ZipFile(filename) as f:
    data = tf.compat.as_str(f.read(f.namelist()[0])).split()
  return data

words = read_data(filename)
print('Data size', len(words))

# Step 2: Build the dictionary and replace rare words with UNK token.
vocabulary_size = 50000

def build_dataset(words): #words in corpus , list
  count = [['UNK', -1]]
  count.extend(collections.Counter(words).most_common(vocabulary_size - 1)) 
  # 因为使用了most_common,所以count中的word，是按照word在文本中出现的次数从大到小排列的
  dictionary = dict()
  for word, _ in count:
    dictionary[word] = len(dictionary)   # assign id to word
  data = list()
  unk_count = 0
  for word in words:
    if word in dictionary:
      index = dictionary[word]
    else:
      index = 0  # dictionary['UNK'] UNK:unknown
      unk_count += 1
    data.append(index) #translate word to id
  count[0][1] = unk_count
  reverse_dictionary = dict(zip(dictionary.values(), dictionary.keys()))
  return data, count, dictionary, reverse_dictionary #data:ids count:list of [word,num] dictionary:word->id ,

data, count, dictionary, reverse_dictionary = build_dataset(words)
del words  # Hint to reduce memory.
print('Most common words (+UNK)', count[:5])
print('Sample data', data[:10], [reverse_dictionary[i] for i in data[:10]])

data_index = 0


# Step 3: Function to generate a training batch for the skip-gram model.
#skip_skip:从span里面取出多少个word， skip_window:|contex(w)| / 2
#span: w上下文的word， 只能从span这个范围中获取
def generate_batch(batch_size, num_skips, skip_window):
  global data_index
  assert batch_size % num_skips == 0
  assert num_skips <= 2 * skip_window   # num_skip? skip_window? skip-gram
  batch = np.ndarray(shape=(batch_size), dtype=np.int32) #batch_size: the number of words in one batch
  labels = np.ndarray(shape=(batch_size, 1), dtype=np.int32)
  span = 2 * skip_window + 1 # [ skip_window target skip_window ]
  buffer = collections.deque(maxlen=span) #buffer用来存取w上下文word的id
  for _ in range(span):
    buffer.append(data[data_index]) # data:ids
    data_index = (data_index + 1) % len(data)
  for i in range(batch_size // num_skips): #how many num_skips in a batch
    target = skip_window  # target label at the center of the buffer
    targets_to_avoid = [ skip_window ] # extract the middle word
    for j in range(num_skips):
      while target in targets_to_avoid:#context中的word，一个只取一次
        target = random.randint(0, span - 1)
      targets_to_avoid.append(target) #
      batch[i * num_skips + j] = buffer[skip_window]
      labels[i * num_skips + j, 0] = buffer[target]
    buffer.append(data[data_index]) #update the buffer, append the next word to buffer
    data_index = (data_index + 1) % len(data)
  return batch, labels #batch: ids [batch_size] lebels:ids [batch_size*1]

batch, labels = generate_batch(batch_size=8, num_skips=2, skip_window=1)
for i in range(8):
  print(batch[i], reverse_dictionary[batch[i]],
      '->', labels[i, 0], reverse_dictionary[labels[i, 0]])
#========================================================
#上面的操作会形成一个这样的输出 batch中存储的是id， 假设我们去skip_size = 4, skip_window = 2
#那么，单词 as 所对应的context的word个数就是4个，所以batch中有4个as， 所对应的就是context中的word
# 12 as -> 195 term
# 12 as -> 5239 anarchism
# 12 as -> 6 a
# 12 as -> 3084 originated
# 6 a -> 12 as
# 6 a -> 3084 originated
# 6 a -> 2 of
# 6 a -> 195 term
#=======================================================
# Step 4: Build and train a skip-gram model.

#在本代码中，batch_size代表的是一个batch中，word的个数，而不是sentense的个数。
batch_size = 128
embedding_size = 128  # Dimension of the embedding vector.
skip_window = 1       # How many words to consider left and right.
num_skips = 2         # How many times to reuse an input(buffer) to generate a label.

# We pick a random validation set to sample nearest neighbors. Here we limit the
# validation samples to the words that have a low numeric ID, which by
# construction are also the most frequent.
valid_size = 16     # Random set of words to evaluate similarity on.
valid_window = 100  # Only pick dev samples in the head of the distribution.
valid_examples = np.random.choice(valid_window, valid_size, replace=False)
num_sampled = 64    # Number of negative examples to sample.

graph = tf.Graph()

with graph.as_default():

  # Input data.
  #在这里，我们只输入word对应的id，假设batch_size是128,那么我们第一次就输入文本前128个word所对应的id
  train_inputs = tf.placeholder(tf.int32, shape=[batch_size])
  #labels和inputs是一样的， 只不过一个是行向量（tensor），一个是列向量（tensor）
  train_labels = tf.placeholder(tf.int32, shape=[batch_size, 1])
  valid_dataset = tf.constant(valid_examples, dtype=tf.int32)

  # Ops and variables pinned to the CPU because of missing GPU implementation
  with tf.device('/cpu:0'):
    # Look up embeddings for inputs.
    embeddings = tf.Variable(
        tf.random_uniform([vocabulary_size, embedding_size], -1.0, 1.0))
    # embedding_look 返回值的shape 是 shape(train_inputs)+shape(embeddings)[1:]
    embed = tf.nn.embedding_lookup(embeddings, train_inputs)

    # Construct the variables for the NCE loss
    nce_weights = tf.Variable(   #every word has a corresponding nce_weight ad nce_biase
        tf.truncated_normal([vocabulary_size, embedding_size],
                            stddev=1.0 / math.sqrt(embedding_size)))
    nce_biases = tf.Variable(tf.zeros([vocabulary_size]))

AttributeError: ignored